#!/data/data/com.termux/files/usr/bin/sh
set -e

SCRIPTNAME=termux-microphone-record

show_usage () {
    echo "Usage: $SCRIPTNAME [args]"
    echo "Record using microphone on your device"
    echo
    echo "-h           Shows this help"
    echo "-d           Start recording w/ defaults"
    echo "-f <file>    Start recording to specific file"
    echo "-l <limit>   Start recording w/ specified limit (in seconds)"
    echo "-i           Get info about current recording"
    echo "-q           Quits recording"
}

ARG_F=""
OPT_F=""
ARG_L=""
OPT_L=""

usage_error () {
    echo
    show_usage
    exit 1
}

sole() {
    if [ "$1 $2" != "-$option $OPTARG" ] || [ $# -gt 2 ]; then
        echo "ERROR: No other options should be specified with -$option!"
        usage_error
    fi
}

call_api () {
    /data/data/com.termux/files/usr/libexec/termux-api MicRecorder "$@"
    exit 0
}

while getopts h,f:,l:,d,i,q option
do
    case "$option" in
        h) sole "$@"
           show_usage
           exit 0
           ;;
        f) dir="$(dirname "$OPTARG")"
           file="$(basename "$OPTARG")"
           dir="$(realpath "$dir")"
           ARG_F="--es file"
           OPT_F="$dir/$file"
           ;;
        # API takes limit in milliseconds
        l) ARG_L="--ei limit"
           OPT_L=$((OPTARG * 1000))
           ;;
        d) sole "$@"
           call_api -a record
           ;;
        i) sole "$@"
           call_api -a info
           ;;
        q) sole "$@"
           call_api -a quit
           ;;
        *) usage_error
           ;;
    esac
done

set --
if [ -n "$ARG_F" ]; then set -- "$@" $ARG_F "$OPT_F"; fi
if [ -n "$ARG_L" ]; then set -- "$@" $ARG_L "$OPT_L"; fi
set -- "$@" -a record

call_api "$@"
