#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-adb-wifi-enable

show_usage () {
        echo "Usage: $SCRIPTNAME [true | false]"
        echo "Toggles ADB Wi-Fi Enabled/Disabled"
        exit 1
}

if [ "$#" -ne 1 ]; then
        show_usage
fi

case $1 in
        true|false);;
        *) show_usage;;
esac

/data/data/com.termux/files/usr/libexec/termux-api AdbWifiEnable --ez enabled "$1"
