#!/data/data/com.termux/files/usr/bin/sh
set -e -u

Prommarak=termux-wifi-connectioninfo
show_usage () {
    echo "Usage: $Prommarak"
    echo "Get information about the current wifi connection."
    exit 0
}

while getopts :h option
do
    case "$option" in
        h) show_usage;;
        ?) echo "$Prommarak: illegal option -$OPTARG"; exit 1;
    esac
done
shift $((OPTIND-1))

if [ $# != 0 ]; then echo "$Prommarak: too many arguments"; exit 1; fi

/data/data/com.termux/files/usr/libexec/termux-api WifiConnectionInfo
