#!/data/data/com.termux/files/usr/bin/bash
set -e -u -f

SCRIPTNAME=termux-notification
show_usage () {
    echo "Usage: termux-notification [options]"
    echo "Display a system notification. Content text is specified using -c/--content or read from stdin."
    echo "Please read --help-actions for help with action arguments."
    echo "  --action action          action to execute when pressing the notification"
    echo "  --alert-once             do not alert when the notification is edited"
    echo "  --button1 text           text to show on the first notification button"
    echo "  --button1-action action  action to execute on the first notification button"
    echo "  --button2 text           text to show on the second notification button"
    echo "  --button2-action action  action to execute on the second notification button"
    echo "  --button3 text           text to show on the third notification button"
    echo "  --button3-action action  action to execute on the third notification button"
    echo "  -c/--content content     content to show in the notification. Will take precedence over stdin."
    echo "  --group group            notification group (notifications with the same group are shown together)"
    echo "  -h/--help                show this help"
    echo "  --help-actions           show the help for actions"
    echo "  -i/--id id               notification id (will overwrite any previous notification with the same id)"
    echo "  --icon icon-name         set the icon that shows up in the status bar. View available icons using"
    echo "                           termux-notification --icon-list; (default icon: event_note)"
    echo "  --icon-list              show list of status bar icons available to termux-notification"
    echo "  --image-path path        absolute path to an image which will be shown in the notification"
    echo "  --led-color rrggbb       color of the blinking led as RRGGBB (default: none)"
    echo "  --led-off milliseconds   number of milliseconds for the LED to be off while it's flashing (default: 800)"
    echo "  --led-on milliseconds    number of milliseconds for the LED to be on while it's flashing (default: 800)"
    echo "  --on-delete action       action to execute when the the notification is cleared"
    echo "  --ongoing                pin the notification"
    echo "  --priority prio          notification priority (high/low/max/min/default)"
    echo "  --sound                  play a sound with the notification"
    echo "  -t/--title title         notification title to show"
    echo "  --vibrate pattern        vibrate pattern, comma separated as in 500,1000,200"
    echo "  --type type              notification style to use (default/media)"
    echo "Media actions (available with --type \"media\"):"
    echo "  --media-next             action to execute on the media-next button"
    echo "  --media-pause            action to execute on the media-pause button"
    echo "  --media-play             action to execute on the media-play button"
    echo "  --media-previous         action to execute on the media-previous button"
    exit 0
}

show_help_actions () {
    echo "This help refers to the arguments to options like --action, --on-delete, --button-1-action and --media-next."
    echo
    echo "All these commands take an action string as their argument, which is fed to \`dash -c\`."
    echo "A few important things must be kept in mind when using actions:"
    echo
    echo "You should use actions that do things outside of the terminal, like --action \"termux-toast hello\"."
    echo "Anything that outputs to the terminal is useless, so the output should either be redirected (--action \"ls > ~/ls.txt\") or shown to the user in a different way (--action \"ls|termux-toast\")."
    echo
    echo "Running more than one command in a single action is as easy as"
    echo "--action \"command1; command2; command3\""
    echo "or"
    echo "--action \"if [ -e file ]; then termux-toast yes; else termux-toast no; fi\"."
    echo
    echo "For anything more complex, you should put your script in a file, make it executable, and use that as the action:"
    echo "--action ~/bin/script"
    echo
    echo "The action is run in a different environment (not a subshell). Thus your environment is lost (most notably \$PATH), and ~/.profile is not sourced either. So if you need your \$PATH you should either:"
    echo " - if the action is a script, set it explicitly in the script (e.g. export PATH=\"\$HOME/bin:\$PATH\")"
    echo " - or use something like --action \"bash -l -c 'command1; command2'\")."
    echo
    echo "On Android N or above, you can use the special variable \$REPLY in your actions to use Android's Direct Reply feature."
    echo "This prompts the user to enter some text directly in the notification, which is then substituted into your action."
    echo " - termux-notification --button1 \"Answer\" --button1-action \"termux-toast \\\$REPLY\""
    echo "will call the action:"
    echo " - termux-toast \"Some text entered by the user\""
    echo "Be careful to escape shell commands correctly for single or double quotes, e.g."
    echo "  --button1-action 'something \$REPLY' or --button1-action \"something \\\$REPLY\""
}

icon_list () {
    echo "Here is the list of icons available to termux-notification. These are based on the Google Material Design Icons."
    echo "We are unable to show a preview of the icons inside the terminal, but they can be previewed on the web at:"
    echo "https://material.io/resources/icons/"
    echo
    echo "3d_rotation                    filter_center_focus          photo_camera"
    echo "ac_unit                        filter_drama                 photo_filter"
    echo "access_alarm                   filter_frames                photo_library"
    echo "access_alarms                  filter_hdr                   photo_size_select_actual"
    echo "access_time                    filter_list                  photo_size_select_large"
    echo "accessibility                  filter_none                  photo_size_select_small"
    echo "accessible                     filter_tilt_shift            picture_as_pdf"
    echo "account_balance                filter_vintage               picture_in_picture_alt"
    echo "account_balance_wallet         find_in_page                 picture_in_picture"
    echo "account_box                    find_replace                 pie_chart"
    echo "account_circle                 fingerprint                  pie_chart_outlined"
    echo "adb                            first_page                   pin_drop"
    echo "add_a_photo                    fitness_center               place"
    echo "add_alarm                      flag                         play_arrow"
    echo "add_alert                      flare                        play_circle_filled"
    echo "add                            flash_auto                   play_circle_outline"
    echo "add_box                        flash_off                    play_for_work"
    echo "add_circle                     flash_on                     playlist_add"
    echo "add_circle_outline             flight                       playlist_add_check"
    echo "add_location                   flight_land                  playlist_play"
    echo "add_shopping_cart              flight_takeoff               plus_one"
    echo "add_to_photos                  flip                         poll"
    echo "add_to_queue                   flip_to_back                 polymer"
    echo "adjust                         flip_to_front                pool"
    echo "airline_seat_flat_angled       folder                       portable_wifi_off"
    echo "airline_seat_flat              folder_open                  portrait"
    echo "airline_seat_individual_suite  folder_shared                power"
    echo "airline_seat_legroom_extra     folder_special               power_input"
    echo "airline_seat_legroom_normal    font_download                power_settings_new"
    echo "airline_seat_legroom_reduced   format_align_center          pregnant_woman"
    echo "airline_seat_recline_extra     format_align_justify         present_to_all"
    echo "airline_seat_recline_normal    format_align_left            print"
    echo "airplanemode_active            format_align_right           priority_high"
    echo "airplanemode_inactive          format_bold                  public"
    echo "airplay                        format_clear                 publish"
    echo "airport_shuttle                format_color_fill            query_builder"
    echo "alarm_add                      format_color_reset           question_answer"
    echo "alarm                          format_color_text            queue"
    echo "alarm_off                      format_indent_decrease       queue_music"
    echo "alarm_on                       format_indent_increase       queue_play_next"
    echo "album                          format_italic                radio"
    echo "all_inclusive                  format_line_spacing          radio_button_checked"
    echo "all_out                        format_list_bulleted         radio_button_unchecked"
    echo "android                        format_list_numbered         rate_review"
    echo "announcement                   format_paint                 receipt"
    echo "apps                           format_quote                 recent_actors"
    echo "archive                        format_shapes                record_voice_over"
    echo "arrow_back                     format_size                  redeem"
    echo "arrow_downward                 format_strikethrough         redo"
    echo "arrow_drop_down                format_textdirection_l_to_r  refresh"
    echo "arrow_drop_down_circle         format_textdirection_r_to_l  remove"
    echo "arrow_drop_up                  format_underlined            remove_circle"
    echo "arrow_forward                  forum                        remove_circle_outline"
    echo "arrow_upward                   forward_10                   remove_from_queue"
    echo "art_track                      forward_30                   remove_red_eye"
    echo "aspect_ratio                   forward_5                    remove_shopping_cart"
    echo "assessment                     forward                      reorder"
    echo "assignment                     free_breakfast               repeat"
    echo "assignment_ind                 fullscreen                   repeat_one"
    echo "assignment_late                fullscreen_exit              replay_10"
    echo "assignment_return              functions                    replay_30"
    echo "assignment_returned            g_translate                  replay_5"
    echo "assignment_turned_in           gamepad                      replay"
    echo "assistant                      games                        reply_all"
    echo "assistant_photo                gavel                        reply"
    echo "attach_file                    gesture                      report"
    echo "attach_money                   get_app                      report_problem"
    echo "attachment                     gif                          restaurant"
    echo "audiotrack                     golf_course                  restaurant_menu"
    echo "autorenew                      gps_fixed                    restore"
    echo "av_timer                       gps_not_fixed                restore_page"
    echo "backspace                      gps_off                      ring_volume"
    echo "backup                         grade                        room"
    echo "battery_20                     gradient                     room_service"
    echo "battery_30                     grain                        rotate_90_degrees_ccw"
    echo "battery_50                     graphic_eq                   rotate_left"
    echo "battery_60                     grid_off                     rotate_right"
    echo "battery_80                     grid_on                      rounded_corner"
    echo "battery_90                     group_add                    router"
    echo "battery_alert                  group                        rowing"
    echo "battery_charging_20            group_work                   rss_feed"
    echo "battery_charging_30            hd                           rv_hookup"
    echo "battery_charging_50            hdr_off                      satellite"
    echo "battery_charging_60            hdr_on                       save"
    echo "battery_charging_80            hdr_strong                   scanner"
    echo "battery_charging_90            hdr_weak                     schedule"
    echo "battery_charging_full          headset                      school"
    echo "battery_full                   headset_mic                  screen_lock_landscape"
    echo "battery_std                    healing                      screen_lock_portrait"
    echo "battery_unknown                hearing                      screen_lock_rotation"
    echo "beach_access                   help                         screen_rotation"
    echo "beenhere                       help_outline                 screen_share"
    echo "block                          high_quality                 sd_card"
    echo "bluetooth_audio                highlight                    sd_storage"
    echo "bluetooth                      highlight_off                search"
    echo "bluetooth_connected            history                      security"
    echo "bluetooth_disabled             home                         select_all"
    echo "bluetooth_searching            hot_tub                      send"
    echo "blur_circular                  hotel                        sentiment_dissatisfied"
    echo "blur_linear                    hourglass_empty              sentiment_neutral"
    echo "blur_off                       hourglass_full               sentiment_satisfied"
    echo "blur_on                        http                         sentiment_very_dissatisfied"
    echo "book                           https                        sentiment_very_satisfied"
    echo "bookmark                       image_aspect_ratio           settings_applications"
    echo "bookmark_border                image                        settings_backup_restore"
    echo "border_all                     import_contacts              settings"
    echo "border_bottom                  import_export                settings_bluetooth"
    echo "border_clear                   important_devices            settings_brightness"
    echo "border_color                   inbox                        settings_cell"
    echo "border_horizontal              indeterminate_check_box      settings_ethernet"
    echo "border_inner                   info                         settings_input_antenna"
    echo "border_left                    info_outline                 settings_input_component"
    echo "border_outer                   input                        settings_input_composite"
    echo "border_right                   insert_chart                 settings_input_hdmi"
    echo "border_style                   insert_comment               settings_input_svideo"
    echo "border_top                     insert_drive_file            settings_overscan"
    echo "border_vertical                insert_emoticon              settings_phone"
    echo "branding_watermark             insert_invitation            settings_power"
    echo "brightness_1                   insert_link                  settings_remote"
    echo "brightness_2                   insert_photo                 settings_system_daydream"
    echo "brightness_3                   invert_colors                settings_voice"
    echo "brightness_4                   invert_colors_off            share"
    echo "brightness_5                   iso                          shop"
    echo "brightness_6                   keyboard_arrow_down          shop_two"
    echo "brightness_7                   keyboard_arrow_left          shopping_basket"
    echo "brightness_auto                keyboard_arrow_right         shopping_cart"
    echo "brightness_high                keyboard_arrow_up            short_text"
    echo "brightness_low                 keyboard_backspace           show_chart"
    echo "brightness_medium              keyboard                     shuffle"
    echo "broken_image                   keyboard_capslock            signal_cellular_0_bar"
    echo "brush                          keyboard_hide                signal_cellular_1_bar"
    echo "bubble_chart                   keyboard_return              signal_cellular_2_bar"
    echo "bug_report                     keyboard_tab                 signal_cellular_3_bar"
    echo "build                          keyboard_voice               signal_cellular_4_bar"
    echo "burst_mode                     kitchen                      signal_cellular_connected_no_internet_0_bar"
    echo "business                       label                        signal_cellular_connected_no_internet_1_bar"
    echo "business_center                label_outline                signal_cellular_connected_no_internet_2_bar"
    echo "cached                         landscape                    signal_cellular_connected_no_internet_3_bar"
    echo "cake                           language                     signal_cellular_connected_no_internet_4_bar"
    echo "call                           laptop                       signal_cellular_no_sim"
    echo "call_end                       laptop_chromebook            signal_cellular_null"
    echo "call_made                      laptop_mac                   signal_cellular_off"
    echo "call_merge                     laptop_windows               signal_wifi_0_bar"
    echo "call_missed                    last_page                    signal_wifi_1_bar"
    echo "call_missed_outgoing           launch                       signal_wifi_1_bar_lock"
    echo "call_received                  layers                       signal_wifi_2_bar"
    echo "call_split                     layers_clear                 signal_wifi_2_bar_lock"
    echo "call_to_action                 leak_add                     signal_wifi_3_bar"
    echo "camera_alt                     leak_remove                  signal_wifi_3_bar_lock"
    echo "camera                         lens                         signal_wifi_4_bar"
    echo "camera_enhance                 library_add                  signal_wifi_4_bar_lock"
    echo "camera_front                   library_books                signal_wifi_off"
    echo "camera_rear                    library_music                sim_card_alert"
    echo "camera_roll                    lightbulb_outline            sim_card"
    echo "cancel                         line_style                   skip_next"
    echo "card_giftcard                  line_weight                  skip_previous"
    echo "card_membership                linear_scale                 slideshow"
    echo "card_travel                    link                         slow_motion_video"
    echo "casino                         linked_camera                smartphone"
    echo "cast                           list                         smoke_free"
    echo "cast_connected                 live_help                    smoking_rooms"
    echo "center_focus_strong            live_tv                      sms"
    echo "center_focus_weak              local_activity               sms_failed"
    echo "change_history                 local_airport                snooze"
    echo "chat                           local_atm                    sort"
    echo "chat_bubble                    local_bar                    sort_by_alpha"
    echo "chat_bubble_outline            local_cafe                   spa"
    echo "check                          local_car_wash               space_bar"
    echo "check_box                      local_convenience_store      speaker"
    echo "check_box_outline_blank        local_dining                 speaker_group"
    echo "check_circle                   local_drink                  speaker_notes"
    echo "chevron_left                   local_florist                speaker_notes_off"
    echo "chevron_right                  local_gas_station            speaker_phone"
    echo "child_care                     local_grocery_store          spellcheck"
    echo "child_friendly                 local_hospital               star"
    echo "chrome_reader_mode             local_hotel                  star_border"
    echo "class                          local_laundry_service        star_half"
    echo "clear_all                      local_library                stars"
    echo "clear                          local_mall                   stay_current_landscape"
    echo "close                          local_movies                 stay_current_portrait"
    echo "closed_caption                 local_offer                  stay_primary_landscape"
    echo "cloud                          local_parking                stay_primary_portrait"
    echo "cloud_circle                   local_pharmacy               stop"
    echo "cloud_done                     local_phone                  stop_screen_share"
    echo "cloud_download                 local_pizza                  storage"
    echo "cloud_off                      local_play                   store"
    echo "cloud_queue                    local_post_office            store_mall_directory"
    echo "cloud_upload                   local_printshop              straighten"
    echo "code                           local_see                    streetview"
    echo "collections                    local_shipping               strikethrough_s"
    echo "collections_bookmark           local_taxi                   style"
    echo "color_lens                     location_city                subdirectory_arrow_left"
    echo "colorize                       location_disabled            subdirectory_arrow_right"
    echo "comment                        location_off                 subject"
    echo "compare_arrows                 location_on                  subscriptions"
    echo "compare                        location_searching           subtitles"
    echo "computer                       lock                         subway"
    echo "confirmation_number            lock_open                    supervisor_account"
    echo "contact_mail                   lock_outline                 surround_sound"
    echo "contact_phone                  looks_3                      swap_calls"
    echo "contacts                       looks_4                      swap_horiz"
    echo "content_copy                   looks_5                      swap_vert"
    echo "content_cut                    looks_6                      swap_vertical_circle"
    echo "content_paste                  looks                        switch_camera"
    echo "control_point                  looks_one                    switch_video"
    echo "control_point_duplicate        looks_two                    sync"
    echo "copyright                      loop                         sync_disabled"
    echo "create                         loupe                        sync_problem"
    echo "create_new_folder              low_priority                 system_update_alt"
    echo "credit_card                    loyalty                      system_update"
    echo "crop_16_9                      mail                         tab"
    echo "crop_3_2                       mail_outline                 tab_unselected"
    echo "crop_5_4                       map                          tablet_android"
    echo "crop_7_5                       markunread                   tablet"
    echo "crop                           markunread_mailbox           tablet_mac"
    echo "crop_din                       memory                       tag_faces"
    echo "crop_free                      menu                         tap_and_play"
    echo "crop_landscape                 merge_type                   terrain"
    echo "crop_original                  message                      text_fields"
    echo "crop_portrait                  mic                          text_format"
    echo "crop_rotate                    mic_none                     textsms"
    echo "crop_square                    mic_off                      texture"
    echo "dashboard                      mms                          theaters"
    echo "data_usage                     mode_comment                 thumb_down"
    echo "date_range                     mode_edit                    thumb_up"
    echo "dehaze                         monetization_on              thumbs_up_down"
    echo "delete                         money_off                    time_to_leave"
    echo "delete_forever                 monochrome_photos            timelapse"
    echo "delete_sweep                   mood_bad                     timeline"
    echo "description                    mood                         timer_10"
    echo "desktop_mac                    more                         timer_3"
    echo "desktop_windows                more_horiz                   timer"
    echo "details                        more_vert                    timer_off"
    echo "developer_board                motorcycle                   title"
    echo "developer_mode                 mouse                        toc"
    echo "device_hub                     move_to_inbox                today"
    echo "devices                        movie                        toll"
    echo "devices_other                  movie_creation               tonality"
    echo "dialer_sip                     movie_filter                 touch_app"
    echo "dialpad                        multiline_chart              toys"
    echo "directions_bike                music_note                   track_changes"
    echo "directions                     music_video                  traffic"
    echo "directions_boat                my_location                  train"
    echo "directions_bus                 nature                       tram"
    echo "directions_car                 nature_people                transfer_within_a_station"
    echo "directions_railway             navigate_before              transform"
    echo "directions_run                 navigate_next                translate"
    echo "directions_subway              navigation                   trending_down"
    echo "directions_transit             near_me                      trending_flat"
    echo "directions_walk                network_cell                 trending_up"
    echo "disc_full                      network_check                tune"
    echo "dns                            network_locked               turned_in"
    echo "do_not_disturb_alt             network_wifi                 turned_in_not"
    echo "do_not_disturb                 new_releases                 tv"
    echo "do_not_disturb_off             next_week                    unarchive"
    echo "do_not_disturb_on              nfc                          undo"
    echo "dock                           no_encryption                unfold_less"
    echo "domain                         no_sim                       unfold_more"
    echo "done_all                       not_interested               update"
    echo "done                           note_add                     usb"
    echo "donut_large                    note                         verified_user"
    echo "donut_small                    notifications_active         vertical_align_bottom"
    echo "drafts                         notifications                vertical_align_center"
    echo "drag_handle                    notifications_none           vertical_align_top"
    echo "drive_eta                      notifications_off            vibration"
    echo "dvr                            notifications_paused         video_call"
    echo "edit                           offline_pin                  video_label"
    echo "edit_location                  ondemand_video               video_library"
    echo "eject                          opacity                      videocam"
    echo "email                          open_in_browser              videocam_off"
    echo "enhanced_encryption            open_in_new                  videogame_asset"
    echo "equalizer                      open_with                    view_agenda"
    echo "error                          pages                        view_array"
    echo "error_outline                  pageview                     view_carousel"
    echo "euro_symbol                    palette                      view_column"
    echo "ev_station                     pan_tool                     view_comfy"
    echo "event_available                panorama                     view_compact"
    echo "event                          panorama_fish_eye            view_day"
    echo "event_busy                     panorama_horizontal          view_headline"
    echo "event_note                     panorama_vertical            view_list"
    echo "event_seat                     panorama_wide_angle          view_module"
    echo "exit_to_app                    party_mode                   view_quilt"
    echo "expand_less                    pause                        view_stream"
    echo "expand_more                    pause_circle_filled          view_week"
    echo "explicit                       pause_circle_outline         vignette"
    echo "explore                        payment                      visibility"
    echo "exposure                       people                       visibility_off"
    echo "exposure_neg_1                 people_outline               voice_chat"
    echo "exposure_neg_2                 perm_camera_mic              voicemail"
    echo "exposure_plus_1                perm_contact_calendar        volume_down"
    echo "exposure_plus_2                perm_data_setting            volume_mute"
    echo "exposure_zero                  perm_device_information      volume_off"
    echo "extension                      perm_identity                volume_up"
    echo "face                           perm_media                   vpn_key"
    echo "fast_forward                   perm_phone_msg               vpn_lock"
    echo "fast_rewind                    perm_scan_wifi               wallpaper"
    echo "favorite                       person_add                   warning"
    echo "favorite_border                person                       watch"
    echo "featured_play_list             person_outline               watch_later"
    echo "featured_video                 person_pin                   wb_auto"
    echo "feedback                       person_pin_circle            wb_cloudy"
    echo "fiber_dvr                      personal_video               wb_incandescent"
    echo "fiber_manual_record            pets                         wb_iridescent"
    echo "fiber_new                      phone_android                wb_sunny"
    echo "fiber_pin                      phone                        wc"
    echo "fiber_smart_record             phone_bluetooth_speaker      web_asset"
    echo "file_download                  phone_forwarded              web"
    echo "file_upload                    phone_in_talk                weekend"
    echo "filter_1                       phone_iphone                 whatshot"
    echo "filter_2                       phone_locked                 widgets"
    echo "filter_3                       phone_missed                 wifi"
    echo "filter_4                       phone_paused                 wifi_lock"
    echo "filter_5                       phonelink                    wifi_tethering"
    echo "filter_6                       phonelink_erase              work"
    echo "filter_7                       phonelink_lock               wrap_text"
    echo "filter_8                       phonelink_off                youtube_searched_for"
    echo "filter_9                       phonelink_ring               zoom_in"
    echo "filter_9_plus                  phonelink_setup              zoom_out"
    echo "filter_b_and_w                 photo_album                  zoom_out_map"
    echo "filter                         photo"
}

OPT_ACTION=""
OPT_ALERT_ONCE=""
OPT_BUTTON1_ACTION=""
OPT_BUTTON1_TEXT=""
OPT_BUTTON2_ACTION=""
OPT_BUTTON2_TEXT=""
OPT_BUTTON3_ACTION=""
OPT_BUTTON3_TEXT=""
OPT_CONTENT=""
OPT_GROUP=""
OPT_ID=""
OPT_ICON=""
OPT_IMAGE_PATH=""
OPT_LED_COLOR=""
OPT_LED_OFF=""
OPT_LED_ON=""
OPT_MEDIA_NEXT=""
OPT_MEDIA_PAUSE=""
OPT_MEDIA_PLAY=""
OPT_MEDIA_PREVIOUS=""
OPT_ONGOING=""
OPT_ON_DELETE_ACTION=""
OPT_PRIORITY=""
OPT_SOUND=""
OPT_TITLE=""
OPT_TYPE=""
OPT_VIBRATE=""

TEMP=`busybox getopt \
     -n $SCRIPTNAME \
     -o hc:i:t: \
     --long action:,alert-once,\
button1:,button1-action:,\
button2:,button2-action:,\
button3:,button3-action:,\
content:,group:,help,help-actions,\
id:,icon:,icon-list,image-path:,\
led-color:,led-on:,led-off:,\
media-previous:,media-next:,media-play:,media-pause:,\
on-delete:,ongoing,\
priority:,\
sound,title:,type:,vibrate: \
     -s bash \
     -- "$@"`
eval set -- "$TEMP"

while true; do
	case "$1" in
		--action) OPT_ACTION="$2"; shift 2;;
		--alert-once) OPT_ALERT_ONCE="true"; shift 1;;
		--button1) OPT_BUTTON1_TEXT="$2"; shift 2;;
		--button1-action) OPT_BUTTON1_ACTION="$2"; shift 2;;
		--button2) OPT_BUTTON2_TEXT="$2"; shift 2;;
		--button2-action) OPT_BUTTON2_ACTION="$2"; shift 2;;
		--button3) OPT_BUTTON3_TEXT="$2"; shift 2;;
		--button3-action) OPT_BUTTON3_ACTION="$2"; shift 2;;
		-c | --content) OPT_CONTENT="$2"; shift 2;;
		--group) OPT_GROUP="$2"; shift 2;;
		-h | --help) show_usage;;
		--help-actions) show_help_actions; exit 0;;
		-i | --id) OPT_ID="$2"; shift 2;;
		--icon) OPT_ICON="$2"; shift 2;;
		--icon-list) icon_list; exit 0;;
		--image-path) OPT_IMAGE_PATH="$2"; shift 2;;
		--led-color) OPT_LED_COLOR="$2"; shift 2;;
		--led-off) OPT_LED_OFF="$2"; shift 2;;
		--led-on) OPT_LED_ON="$2"; shift 2;;
		--media-next) OPT_MEDIA_NEXT="$2"; shift 2;;
		--media-pause) OPT_MEDIA_PAUSE="$2"; shift 2;;
		--media-play) OPT_MEDIA_PLAY="$2"; shift 2;;
		--media-previous) OPT_MEDIA_PREVIOUS="$2"; shift 2;;
		--on-delete) OPT_ON_DELETE_ACTION="$2"; shift 2;;
		--ongoing) OPT_ONGOING="true"; shift 1;;
		--priority) OPT_PRIORITY="$2"; shift 2;;
		--sound) OPT_SOUND="true"; shift 1;;
		-t | --title) OPT_TITLE="$2"; shift 2;;
		--type) OPT_TYPE="$2"; shift 2;;
		--vibrate) OPT_VIBRATE="$2"; shift 2;;
		--) shift; break ;;
	esac
done

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi

if [ "$OPT_ONGOING" == true ] && [ -z "$OPT_ID" ]; then
	echo "Ongoing notifications without an ID are not removable."
	echo "Please set an id with --id \"string\"."
	exit 1
fi

set --
if [ -n "$OPT_ACTION" ]; then set -- "$@" --es action "$OPT_ACTION"; fi
if [ -n "$OPT_ALERT_ONCE" ]; then set -- "$@" --ez alert-once "$OPT_ALERT_ONCE"; fi
if [ -n "$OPT_BUTTON1_ACTION" ]; then set -- "$@" --es button_action_1 "$OPT_BUTTON1_ACTION"; fi
if [ -n "$OPT_BUTTON1_TEXT" ]; then set -- "$@" --es button_text_1 "$OPT_BUTTON1_TEXT"; fi
if [ -n "$OPT_BUTTON2_ACTION" ]; then set -- "$@" --es button_action_2 "$OPT_BUTTON2_ACTION"; fi
if [ -n "$OPT_BUTTON2_TEXT" ]; then set -- "$@" --es button_text_2 "$OPT_BUTTON2_TEXT"; fi
if [ -n "$OPT_BUTTON3_ACTION" ]; then set -- "$@" --es button_action_3 "$OPT_BUTTON3_ACTION"; fi
if [ -n "$OPT_BUTTON3_TEXT" ]; then set -- "$@" --es button_text_3 "$OPT_BUTTON3_TEXT"; fi
if [ -n "$OPT_GROUP" ]; then set -- "$@" --es group "$OPT_GROUP"; fi
if [ -n "$OPT_ID" ]; then set -- "$@" --es id "$OPT_ID"; fi
if [ -n "$OPT_ICON" ]; then set -- "$@" --es icon "$OPT_ICON"; fi
if [ -n "$OPT_IMAGE_PATH" ]; then set -- "$@" --es image-path "$OPT_IMAGE_PATH"; fi
if [ -n "$OPT_LED_COLOR" ]; then set -- "$@" --es led-color "$OPT_LED_COLOR"; fi
if [ -n "$OPT_LED_OFF" ]; then set -- "$@" --ei led-off "$OPT_LED_OFF"; fi
if [ -n "$OPT_LED_ON" ]; then set -- "$@" --ei led-on "$OPT_LED_ON"; fi
if [ -n "$OPT_MEDIA_NEXT" ]; then set -- "$@" --es media-next "$OPT_MEDIA_NEXT"; fi
if [ -n "$OPT_MEDIA_PAUSE" ]; then set -- "$@" --es media-pause "$OPT_MEDIA_PAUSE"; fi
if [ -n "$OPT_MEDIA_PLAY" ]; then set -- "$@" --es media-play "$OPT_MEDIA_PLAY"; fi
if [ -n "$OPT_MEDIA_PREVIOUS" ]; then set -- "$@" --es media-previous "$OPT_MEDIA_PREVIOUS"; fi
if [ -n "$OPT_ONGOING" ]; then set -- "$@" --ez ongoing "$OPT_ONGOING"; fi
if [ -n "$OPT_ON_DELETE_ACTION" ]; then set -- "$@" --es on_delete_action "$OPT_ON_DELETE_ACTION"; fi
if [ -n "$OPT_PRIORITY" ]; then set -- "$@" --es priority "$OPT_PRIORITY"; fi
if [ -n "$OPT_SOUND" ]; then set -- "$@" --ez sound "$OPT_SOUND"; fi
if [ -n "$OPT_TITLE" ]; then set -- "$@" --es title "$OPT_TITLE"; fi
if [ -n "$OPT_TYPE" ]; then set -- "$@" --es type "$OPT_TYPE"; fi
if [ -n "$OPT_VIBRATE" ]; then set -- "$@" --ela vibrate "$OPT_VIBRATE"; fi

if [ -n "$OPT_CONTENT"  ] || [ -t 0 ]; then
	# we either have some content, so it takes precedence over STDIN
	# or have no STDIN, so we must use content even if empty
	echo "$OPT_CONTENT" | /data/data/com.termux/files/usr/libexec/termux-api Notification "$@"
else # use STDIN
	/data/data/com.termux/files/usr/libexec/termux-api Notification "$@"
fi
