#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-telephony-call
show_usage () {
    echo "Usage: $SCRIPTNAME <number>"
    echo "Call a telephony number."
    exit 0
}

while getopts :h option
do
    case "$option" in
	h) show_usage;;
	?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

if [ $# = 1 ]; then
	/data/data/com.termux/files/usr/libexec/termux-api TelephonyCall --es number "$1"
else
	echo "$SCRIPTNAME: No single number to call specified." >&2
	exit 1
fi
