#!@TERMUX_PREFIX@/bin/sh
set -e -u

show_usage () {
    echo "Usage: ${0##*/} [-c camera-id] output-file"
    echo "Take a photo and save it to a file in JPEG format."
    echo "  -c camera-id  ID of the camera to use (see ${0##*/}), default: 0"
    exit 0
}


PARAMS=""
while getopts :hc: option
do
    case "$option" in
        h) show_usage;;
        c) PARAMS="--es camera $OPTARG";;
        ?) echo "${0##*/}: illegal option -$OPTARG"; exit 1;
    esac
done
shift $((OPTIND-1))

if [ $# = 0 ]; then echo "${0##*/}: missing file argument"; exit 1; fi
if [ $# != 1 ]; then echo "$${0##*/}: too many arguments"; exit 1; fi

touch "$1"
PARAMS="$PARAMS --es file `realpath $1`"

@TERMUX_PREFIX@/libexec/termux-api CameraPhoto $PARAMS
