#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-clipboard-set
show_usage () {
    echo "Usage: $SCRIPTNAME [text]"
    echo "Set the system clipboard text. The text to set is either supplied as arguments or read from stdin if no arguments are given."
    exit 0
}

while getopts :h option
do
    case "$option" in
	h) show_usage;;
	?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

CMD="/data/data/com.termux/files/usr/libexec/termux-api Clipboard -e api_version 2 --ez set true"
if [ $# = 0 ]; then
	$CMD
else
	echo -n "$@" | $CMD
fi

